# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install wheel
        python -m pip install --upgrade pip
        pip install xlrd pylint pytest
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        # stop the build if there are errors in pylint check
        pylint --ignore-patterns=*Lexer.py,*Parser.py,*ParserListener.py --disable=r0903 **/*.py
    - name: Test with pytest
      run: |
        pytest
